services:
    iot-dev:
        image: st34lths0/iot_dev:iot_dev_final
        container_name: iot_final
        tty: true
        working_dir: "/"
        environment:
            - DISPLAY=:100
        volumes:
            - ./project_files/project_devel/:/root/:Z
        entrypoint: ["/bin/bash", "-lc", "source /root/project_files/root/.bashrc && exec /bin/bash"]
        network_mode: host
        stdin_open: true
        deploy:
            resources:
                limits:
                    memory: 4g

    ros:
        image: st34lths0/iot_dev:ros_final
        container_name: ros
        network_mode: host
        entrypoint: ["/bin/bash","-lc", "exec /bin/bash" ]
        stdin_open: true
        volumes:
        - ./rosenv/ssl:/root/stoopidHome/src/data_sink/ssl/:rw,Z

    mosquitto-broker:
        image: st34lths0/iot_dev:mqtt_final
        container_name: mqtt-broker
        volumes:
        - /mqtt/config/:/mosquitto/config/:rw,Z
        - /mqtt/data/:/mosquitto/data/:rw,Z
        - /mqtt/log/:/mosquitto/log/:rw,Z
        - /mqtt/ca.crt:/mosquitto/ca.crt:rw,Z
        - /mqtt/server.key:/mosquitto/server.key:rw,Z
        - /mqtt/server.crt:/mosquitto/server.crt:rw,Z
        network_mode: host
        command: mosquitto -c /mosquitto/config/mosquitto.conf -v
        restart: unless-stopped
    

    homeassistant:
        container_name: homeassistant
        image: st34lths0/iot_dev:ha_final
        environment:
            - DISPLAY:101
        volumes:
        - ./HA/config/:/config:Z
        - /etc/localtime:/etc/localtime:ro
        - /run/dbus:/run/dbus:ro
        restart: unless-stopped
        privileged: true
        network_mode: host
        deploy:
            resources:
                limits:
                    memory: 2g
