services:
    iot-dev:
        image: st34lths0/iot_dev:iot_dev
        container_name: iot_final
        tty: true
        working_dir: "/"
        environment:
            - DISPLAY=:100
        volumes:
            # - ~/docker_data:/root/host_data
 
            - /home/absurdity/Desktop/project_files/project_devel/:/root/:Z
        entrypoint: ["/bin/bash", "-lc", "source /root/project_files/root/.bashrc && exec /bin/bash"]
        network_mode: host
        stdin_open: true
        deploy:
            resources:
                limits:
                    memory: 4g
        devices:
            - /dev/ttyUSB0
            - /dev/ttyUSB1
    ros:
        image: rosenv
        container_name: ros
        network_mode: host
        entrypoint: ["/bin/bash","-lc", "exec /bin/bash" ]
        stdin_open: true
        volumes:
        - /home/absurdity/Desktop/project_files/rosenv/:/root/:rw,Z

    mosquitto-broker:
        image: st34lths0/iot_dev:mqtt_final
        container_name: mqtt-broker
        volumes:
        - /home/absurdity/Desktop/project_files/mqtt/config/:/mosquitto/config/:rw,Z
        - /home/absurdity/Desktop/project_files/mqtt/data/:/mosquitto/data/:rw,Z
        - /home/absurdity/Desktop/project_files/mqtt/log/:/mosquitto/log/:rw,Z
        # - ~/Desktop/project_files/mqtt/mqtt_passwd:/mosquitto/passwd:rw
        - /home/absurdity/Desktop/project_files/mqtt/ca.crt:/mosquitto/ca.crt:rw,Z
        - /home/absurdity/Desktop/project_files/mqtt/server.key:/mosquitto/server.key:rw,Z
        - /home/absurdity/Desktop/project_files/mqtt/server.crt:/mosquitto/server.crt:rw,Z  
        network_mode: host
        command: mosquitto -c /mosquitto/config/mosquitto.conf -v
        restart: unless-stopped
    

    homeassistant:
        container_name: homeassistant
        image: st34lths0/iot_dev:ha_final
        environment:
            - DISPLAY:101
        volumes:
        - /home/absurdity/Desktop/project_files/HA/config/:/config:Z
        - /etc/localtime:/etc/localtime:ro
        - /run/dbus:/run/dbus:ro
        restart: unless-stopped
        privileged: true
        network_mode: host
        deploy:
            resources:
                limits:
                    memory: 4g
