serve_water:
  sequence:
  - action: mqtt.publish
    metadata: {}
    data:
      evaluate_payload: false
      qos: '1'
      retain: true
      topic: painlessMesh/to/2735795353
      payload: PUMP_ON
  alias: Serve Water
  description: ''
serve_food:
  sequence:
  - action: mqtt.publish
    metadata: {}
    data:
      evaluate_payload: false
      qos: '1'
      retain: true
      topic: painlessMesh/to/2735795353
      payload: STEPPER_ON
  alias: Serve Food
  description: ''
